### ISSUE TITLE
Standardize use of quotation marks in lesson

### ISSUE THREAD

**Issue by mimishu** [swcarpentry/shell-novice#1009]
Hi there, in reviewing the lesson of http://swcarpentry.github.io/shell-novice/07-find/index.html I got really confused with the uses of single quote vs. double quotes in the command examples, for example: 

$ grep -w "is not" haiku.txt 
$ grep -E '^.o' haiku.txt

I imagine double quotes are used around words and single quotes are used around characters? There is no explanation on differences of their uses anywhere in this lesson and I think it will be useful for novice learners. I suggest adding a sentence explaining their uses, for example (from https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash):

"Single quotes won't interpolate anything, but double quotes will. For example: variables, backticks, certain \ escapes, etc. Enclosing characters in single quotes ( ' ) preserves the literal value of each character within the quotes. A single quote may not occur between single quotes, even when preceded by a backslash."

I hope this helps! Best, Shu (shu.liu@uci.edu)

**Comment by gcapes** [comment]
Thanks for bringing this up! 
While there is this difference in behaviour between single and double quotes, I don't think it actually makes a difference for any of the `grep` or `find` examples in the lesson - indeed I think most of them run just fine with no quotes at all.

I agree that using different quote types for different examples, and even within the same example does rather raise the question as to why. Perhaps it would be good to stick with double quotes throughout for consistency and to reduce this distraction?

**Comment by gdevenyi** [comment]
Good catch on these small details.

For the purposes of these lessons, we should unify for a single type. I don't believe we cover the difference and I think that would be out-of-scope of this novice-level lesson.

**Comment by gcapes** [comment]
Let's stay with double quotes - I think they are the first type introduced, and are more frequently used over the episodes.

**Comment by jttkim** [comment]
The difference is that single quotes preserve the literal value of each character while there are exceptions for double quotes, most notably `$` which retains its special role as a variable de-referencing operator.

I think it makes sense to mention this briefly in the episode. This is mainly because in my experience, learners are very likely to find examples using single and double quotes somewhere in the web, and in the majority of workshops (Carpentry or otherwise), questions / remarks along the lines "I found out that I can also use single / double quotes and it seems to work just as well" will surface.

If only one type of quotes is to be used consistently throughout the lesson I'd argue for that to be the single quote, as it's simpler. In practice, it will reduce the chance of learners randomly trying something like `echo "bash for ca$h"`, and then puzzling over why the `$h` part disappears.

**Comment by gcapes** [comment]
@jttkim 
Good argument - I'd be happy to go with single quotes. Shall we go with single quotes then, leaving any discussion of double vs single quotes to be raised via red sticky notes?

**Comment by gdevenyi** [comment]
Sure, lets standardize on single quotes for the purposes of the lesson.

**Comment by mimishu** [comment]
I agree on the motion of using single quotes across the examples in the novice lesson. I understand we are not looking to adding additional concepts in the lesson, but echoing what jttkim said I think having one sentence in the episode briefly explaining the difference of using single vs. double quotes in command line writing would be helpful to novice learners. Thank you all for your input!

**Comment by gcapes** [comment]
Thread resurrection!

I just started trying to fix this and realised a couple of things:
1. We have to use double quotes in e.g. the loops and scripts episodes, because we want to use variable substitution and protect against spaces in the name, so "$variable" works, but '$variable' won't. So we can't use single quotes throughout this lesson.
2. The grep examples all work with double or single quotes, so we *could* standardise on double quotes, because this *is* a novice lesson and that would avoid introducing a new concept.

Or we could add a concept and explain that double quotes allow variable substitution but single quotes don't, and as such it might be better to use single quotes with grep but not in the loop or script examples of variable substitution. However, all the grep examples work with either type of quote, so we would need a credible example of when it does make a difference in order to demonstrate it.

As a result of this, I'm in favour of the double quotes. Any objections or other thoughts before I get going on this?

**Comment by T0T4R4** [comment]
In western languages, a single quote is an apostrophe while a double quote is used for quoting, hence delimiting a sequence of characters (called a string in computer programming).

Traditionally in programming, single quote were characters delimiters, while double quote were used for delimiting strings (chars arrays). I'm talking about C-derived languages, with a strict rule on these usages.

These sort of discussions are flowing on the web whether which one should preferably be chosen as good practice. The polluting factor from my point of view, comes from lazy languages which tolerates both to be string delimiters. 

In order to provide student with good habits, all-around usable in multiple contexts, I would suggest sticking to double quotes for string delimiters.

**Comment by jttkim** [comment]
As far as I can tell, the `"$variable"` construct is required and expressly introduced in the "Spaces in Names" part of the loops episode only. Otherwise, the code examples use `$variable` (i.e. no quotes), and the lesson context is designed so this will be good enough (i.e. no file names with whitespace in them etc.). So one solution would be to introduce double quotes only in this context, and to use variables without quotes around them in general. This would allow to use single quotes where necessary, and to keep things simple.

On the other hand, if we want to get learners started to use `"$variable"` right from the start, we'll need to explain that the dollar (and also the curly braces when used around the name) are not quoted, in the sense that they are dereferenced. Personally I like this idea as I use quotes around variables myself, in the interest of defensive programming.

However, this does add some cognitive load and as the lesson is already rather intense, I think the argument for keeping things simple has some weight too.

Finally, in looking into this I noticed that `"$@"` is introduced in the shell scripts episode. This is, in fact, one of the more obscure features of bash, in that double quotes around `$@` behave differently from "normal" variables (I had to look that up in the man page to remind myself). I therefore think this should definitely be reviewed to either explain this rather peculiar special case, or to remove this specific feature altogether, again in the interest of keeping things simple.

Overall my gut feeling is that simplifying matters by scaling back the extent of introducing and discussing quotes makes more sense, but knowing that proper use of quotes is important in real life shell usage I would not be unhappy with explaining double quotes and using them consistently in the shell lesson.

**Comment by gcapes** [comment]
Thanks for the input. It's looking a lot like double quotes throughout, but what is the special behaviour of double quotes in `"$@"`?

**Comment by jttkim** [comment]
From the bash man page:

       @      Expands to the positional parameters, starting from  one.   When
              the  expansion  occurs  within  double  quotes,  each  parameter
              expands to a separate word.  That is, "$@" is equivalent to "$1"
              "$2"  ...   If the double-quoted expansion occurs within a word,
              the expansion of the first parameter is joined with  the  begin‐
              ning  part  of  the original word, and the expansion of the last
              parameter is joined with the last part  of  the  original  word.
              When  there  are no positional parameters, "$@" and $@ expand to
              nothing (i.e., they are removed).

The same exceptional handling applies to `$*`. As far as I can tell  this is because these two variables are populated from a script's command line via the argument vector, in which they are provided already tokenised (i.e. each argument vector element is a token, which may contain white space and other separator characters). Therefore, in `$*` and `$@` whitespaces can be parts of tokens, while that's not possible in principle, for any other "normal" variable -- even if the normal variable is created as a "copy" of `$@`, as demonstrated by this script:
```
#!/bin/bash

xList="$@"

echo '$xList quoted':
for x in "$xList" ; do
    echo x: $x
done
echo
echo '$xList unquoted':
for x in $xList ; do
    echo x: $x
done
echo
echo '$@'
for x in "$@" ; do
    echo @: $x
done
```
which gives e.g.
```
$ ./at.sh some.txt other.txt 'hello world.txt'
$xList quoted:
x: some.txt other.txt hello world.txt

$xList unquoted:
x: some.txt
x: other.txt
x: hello
x: world.txt

$@
@: some.txt
@: other.txt
@: hello world.txt
```
The fact that you do get `hello world.txt` as one word from `$@` while you can never get that from any normal variable will drive learners mad. It sure would have driven me mad anytime before I got reasonably proficient with `flex`.

So my suggestions are: (1) remove the `$@` part (or keep it in the example but remove / change the "we should put `$@` in double quotes..." part, as it suggests that learners should be able to deduce that from what's covered in the lesson), and (2) either introduce the rationale for `"$variable"` and then use that consistently, as you suggest, or, if you feel that's unnecessary complexity, don't use quotes unless necessary, and isolate the cases where they're necessary in one or two callout boxes.

**Comment by gcapes** [comment]
Thanks @jttkim, that was very useful.

Yes, the lesson files don't require quoted variables at all. This is nice and simple. Double quoting variables has a lot of real-world usefulness, so I think it would be a shame not to include this.

I see your point about copies of `"$@"`, or manually created variables, and the difference in behaviour when double quoting `$@` is that spaces are protected within each element, but not the list as a whole. It hadn't actually occurred to me that this behaviour was different to quoting a single (non-list) variable), so perhaps learners don't get tripped up on it either. *However* I am definitely in favour of changing the wording to explain this, rather than suggesting that learners should already be able to infer this from what we've already covered.

I'll get on with the PR now :)

**Comment by gcapes** [comment]
Having re-read episode 6, I'm not sure I really agree with (1) above. The explanation given is correct and concise, and I'm not sure how we could improve the wording?

> We also should put `$@` inside double-quotes
to handle the case of arguments containing spaces
(`"$@"` is equivalent to `"$1"` `"$2"` ...)

**Comment by jttkim** [comment]
The wording is factually correct. My concern is that there's no mention that this is a special behaviour that only applies to the special variables `$*` and `$@`, and so learners will despair trying to create the same behaviour with other non-special variables. (Or, worse, if they're tenacious, end up with dodgy solutions involving `eval`, backticks, creating temporary files with shell code snippets and sourcing these -- I've seen all of these "in the wild", and admit having devised and used dodgy stuff using some of these ideas myself, in the past.)

At the point where we introduce `"$variable"`, we need to clearly state that this (normally) expands to one token only, and that therefore the using `"$variable"` is a good defensive practice that ensures shell code will work if variables end up containing strings with white space and other special characters. I think that this should also be illustrated with a simple example, along the lines of
```
filename='hello world.txt'
cp $filename examples/
```
will not work, as `cp` will look for files `hello` and `world.txt`. (I notice that this involves introducing single quotes but I can't think of any way to avoid that right now.) Then, in episode 6, I suggest to change the wording to something like "As an exception, `"$@"` expands to multiple tokens, it is equivalent to `"$1" "$2" ...`. This special feature allows us to use `"$@"` for passing the parameters given to a shell script on to a program, such as `wc`".

**Comment by gcapes** [comment]
I've tried for a good while to reword this section, but each time I expand the explanation it gets too long and raises further questions. I think this might just be out of scope for a novice lesson, and sacrificing detail for clarity might win out.

**Comment by gdevenyi** [comment]
Agree with @gcapes that the details of such bits are out-of-scope. I believe somewhere in the lesson (and I have always emphasized) that spaces and special characters in filenames causes much pain, which can be handled, but is very much not worth the effort compared to fixing the names at the beginning.
