### ISSUE TITLE
Customising Git Bash

### ISSUE THREAD

**Issue by nancyrouleurs** [swcarpentry/shell-novice#1021]
It would be useful for the learner to know how to customise the Git Bash (basic options) for example how to change the font size, background colour, text colour. I came across this while I was preparing the teaching demonstration. I preferred having a white background, large font size and black text. The learners may have a question on why the instructor's terminal looks different. Adding the short section under the Setup or Introducing the Shell would be great for learners.

**Comment by gcapes** [comment]
Thanks for the issue!

There are two issues in here though - could you edit this one so that it's about setup, and create another for auditing the lesson for demotivating use of 'just'.

**Comment by gcapes** [comment]
Thanks for separating these out. I would think that discussing customisation of the shell opens a bit of a can of worms. If we describe how to edit preferences on Git Bash, then we should also cover terminal on Ubuntu, CentOS, Mac ... this would add a lot of extra material to the lesson.

Given that customisation of the shell doesn't address any learning objectives - i.e. it isn't required in order to understand any of the concepts introduced in the lesson, I think we should leave that can of worms unopened.
