### ISSUE TITLE
Output of `tree` command without introducing it to students.

### ISSUE THREAD

**Issue by joasilva** [swcarpentry/shell-novice#1062]
Hi, please check [lesson 3](http://swcarpentry.github.io/shell-novice/03-create/index.html#more-on-wildcards)

Under "More on Wildcards", a few examples of `tree` output appear, without `tree` having been introduced to students so far.

I suggest that `tree` is succinctly introduced at this point.

Cheers,
João

**Comment by gcapes** [comment]
I would hope that this representation would be fairly self-explanatory at this point in the lesson, having already encountered some file system diagrams, but would be happy to review a PR which addresses this concern.

**Comment by T0T4R4** [comment]
Unfortunately, looks like `tree` is only a Linux thing. Not available on Mac unless you install it with `brew`.
I find it quite annoying that some part of the tutorial refers to Mac environment, while others to Linux environment. It should be consistent, targeting a unique environment, which in my opinion should be Linux.

**Comment by gcapes** [comment]
Ok so how difficult to interpret do we think the output from `tree` is?

**Comment by lkov0** [comment]
In my opinion, since the `tree` command is not specifically invoked in the lesson and is only used to represent the directory structure, the `tree` output will not be confusing to learners. Most people who have navigated a filesystem on a GUI are probably familiar with what the diagram represents. I think it's fine how it is and instructors should be able to gauge their audience to determine if further explanation is needed. 
However, It could potentially be made clearer by changing: "Sam has a directory containing calibration data, datasets, and descriptions of the datasets:" to "Sam has a directory containing calibration data, datasets, and descriptions of the datasets. The directory structure looks like this:" but like I said, it seems clear enough for most learners the way it is.

**Comment by gcapes** [comment]
I'm happy enough that this depiction is fairly self-explanatory. If someone thinks it needs an improvement to the wording as suggested above, I'll review a PR, but I'm closing this issue for no.w
