### ISSUE TITLE
Ep3. mv ls output clarification

### ISSUE THREAD

**Issue by shannon518** [swcarpentry/shell-novice#1116]
In the [Moving files and directories section](http://swcarpentry.github.io/shell-novice/03-create/index.html#moving-files-and-directories), `mv thesis/quotes.txt . ` moves this file to the current working directory. `ls thesis` would then have no output as the file was moved out of that directory. 
> Further, `ls` with a filename or directory name as an argument only lists that file or directory. We can use this to see that quotes.txt is still in our current directory: 
Bash ls quotes.txt 
Output quotes.txt"

As a new user, this was not quite clear to me. Does this mean that `quotes.txt` would not show up in the output if it was not in the current working directory? Maybe it would help to clarify this if this is the case. Possibly, `ls` with a filename or directory name as an argument only lists that file or directory in the output if it is contained in the current working directory. The sentence alone was a bit confusing.

**Comment by gcapes** [comment]
Hi @shannon518, and thanks for the issue.

Would an example before the exercise 'Moving Files to a new folder' fix this issue? Something like
```
~ $ ls made-up-file
ls: cannot access 'made-up-file': No such file or directory
~ $ 
```
And a sentence to say that if

**Comment by matthewabrown** [comment]
I think these are natural questions that novices should be asking at this point in the Unix Shell lessons. They should know the definition of what to expect when issuing an `ls` or `mv` command, but the concepts are certainly rather amorphous or not sharply understood. By gradually including more examples like this which are common and practical, learners are given the opportunity to develop a sharper understanding of the usage of commands. 

I like @gcapes suggestion because it simultaneously provides an example of a common error message, validates the result of the `mv` command, and reinforces a common usage of the `ls` command. 

Something like this could be added
`~ $ ls thesis/quotes.txt
ls: cannot access 'thesis/quotes.txt': No such file or directory
~ $ `

A similar usage and consequence is given in the section on `rm`, though. This doesn't both me too much, because the duplication may be useful and the additional length is worth the clarity and forcing the concept instead of glossing over it. 

A contributing factor may be that this is about the point at which many learners will be hitting a fatigue point, assuming they have been through lessons 1-Introducing the Shell & 2-Navigating Files and Directories and now this one in sequence. They're now holding the half a dozen concepts and half a dozen commands in short-term memory and the lesson needs to provide solid attachments points to a mental model.

One last option may be to reorder the commands in the lesson to first cover `cp`, then `rm`, and finally `mv`. While we explain `mv` as a "rename" in concept, this is only true in a special case (albeit a very common special case). More generally, `mv` acts as a simultaneous `cp` then `rm` packaged into a single command. I think that explaining that level of operation is going into the weeds and should be avoided, but sequencing things this way might help provide the correct scaffolding for future understanding.
