### ISSUE TITLE
Ep04: Exercise disrupts flow

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#1188]
The exercise **What Does sort -n Do?** has a brief introduction which is easy to miss after the **output page by page** callout. 
Do we need the **output page by page** callout? Or could it be moved? 

The slightly buried introduction makes the exercise seem to come out of nowhere, only for the purpose to be revealed afterwards. This exercise would benefit from a clearer introduction to let us know that we're going to use what we learn in the exercise. 
Something like
> Next we'll use the sort command to sort the contents of the `lengths.txt` file. But first we'll need to learn a little about the `sort` command

**Comment by iaviney** [comment]
I think that the tidbit about "output page by page" is useful to introduce the command less, which is very useful for larger files. I wouldn't want learners to miss out on this note, so I don't think that it should be removed. However, I think it could be appropriate to move this callout either to the bottom of the episode, or into another episode where 'cat' is used more often. 
For instance, I think it could be moved to episode 5 after the sentence "As a final check, she opens another terminal window, goes into north-pacific-gyre/2012-07-03, and uses cat stats-NENE01729B.txt to examine one of the output files. It looks good, so she decides to get some coffee and catch up on her reading." since this sentence directly references the use of 'cat' to check the contents of a file.

**Comment by gcapes** [comment]
I think this can be sorted by moving the sub-headings around. They're not quite in the right places, and if `sort` goes at the start of the section it won't get overlooked.
