### ISSUE TITLE
Institutional OneDrive backup means ~/Desktop may not match Windows desktop

### ISSUE THREAD

**Issue by elichad** [swcarpentry/shell-novice#1259]
I ran into this at a recent workshop within my organisation. Some attendees had set up their machine so that all their files are stored on our institutional OneDrive. Turns out that when you do this, it actually changes your "desktop" folder (i.e. the folder whose files get displayed on your Windows GUI desktop) to a folder on OneDrive.

The ~/Desktop folder still exists on your machine and can be used for the workshop, but you can no longer compare it to the Windows desktop to see that e.g. new folders appear there. This is not particularly intuitive and did cause some confusion among those attendees with this setup. They had to dig through the bowels of their filesystem to figure out where the OneDrive desktop folder was stored.

It might be worth making a note of this in the course material/instructor notes, and providing the typical path to the OneDrive desktop so that people can find it if need be.

**Comment by deppen8** [comment]
Thanks for sharing this experience, @elichad. Cloud storage, especially enterprise/institutional managed cloud storage, can definitely make the lesson bumpy.

I don't have access to a setup like this, but I'd be happy to look at a PR for the Instructor Notes. Is that something you can put together?

**Comment by chendaniely** [comment]
just curious, if the students run `explorer .` while in the `~/Desktop` folder. does the explorer window open up in the correct OneDrive desktop? or still the local `C:\` desktop?

**Comment by jvanvinkenroye** [comment]
I have tried to set up a suitable configuration. If not configured otherwise, the Desktop folder would be located under c:\User\Username\Desktop. 

When your Computer to an enterprise OneDrive (or it would be setup for you in advance), the "Document", "Pictures" and "Desktop" Folder would be moved to new Onedrive Folder. Assuming your user folder would be c":\User\Username\" the OneDrive Folder would be "c:\User\Username\OneDrive - NameOfEnterprise". 

As a result, the Desktop Folder would no longer be "c:\User\Username\Desktop" but "c:\User\Username\OneDrive - NameOfEnterprise\Desktop"

An easy way to spot if the computer is using this kind of configuration would be files, folders or links on the desktop. Usually the icon contains a pointer if it is a link or just the plain icon if the file is just saved in the folder "Desktop". Files synced with OneDrive contain an additional blue circle of pointers.

**Comment by elichad** [comment]
My colleague (thanks @willfurnell) has confirmed the same configuration as @jvanvinkenroye. I'll try and put a PR together to note this somewhere.
