### ISSUE TITLE
Ep3: Should exercises be runnable?

### ISSUE THREAD

**Issue by katma889** [swcarpentry/shell-novice#1281]
[This episode](https://swcarpentry.github.io/shell-novice/03-create/index.html) talks about moving files and directories with very nice examples. 
However, it is a bit confusing when we try to list folders `analyzed` and `raw` with their contents `fructose.dat`, `glucose.dat`, `maltose.dat`, `sucrose.dat`. Because those directories and files are not in our example datasets  `shell-lesson-data` and there is nothing mentioned about creating them beforehand. As the lesson is specially designed for novice learners, I think it would be helpful if those folders are included in the `shell-lesson-data`.

Thank you,
Mandira

**Comment by fiveop** [comment]
This is true for more exercises. I understand that (most of) those exercises (without corresponding sample data) are supposed to be solved just by thinking about them. However, when I gave a course on part of this lessons' material, I still provided the students with additional sample data for those exercises, so that learners can test their hypothesis and play around with the commands.

**Comment by gcapes** [comment]
Thanks for bringing this up. Great minds .... (#924). Perhaps we can continue the discussion on the other issue?
