### ISSUE TITLE
Lesson 3: here documents in create files a different way

### ISSUE THREAD

**Issue by JimCircadian** [swcarpentry/shell-novice#1311]
Whilst having a look at the [Create a text file](https://swcarpentry.github.io/shell-novice/03-create/index.html#creating-files-a-different-way) section I was interested in why `nano` and `touch` was used, but use of a ["here document"](https://tldp.org/LDP/abs/html/here-docs.html) to populate the touched file with equivalent content wasn't? This would be a really interesting method to introduce redirection, the concept of std{in,out} and the power of shells to produce file content based on command outputs, which of course becomes surpremely useful when you get into pipelines and scripts in later lessons:

```
cat <<EOF >draft.txt
It's not publish or perish any more,
it's "share and strive".
EOF
```

Perhaps this could be an interesting addition for users after the introduction of `touch`, to say how you can produce content into the empty file? 

I appreciate reading on further that the next lesson introduces output capturing, which we could potentially mention in any inclusion of this in Lesson 3. Might be a good way of whetting the appetite! 😄 Either that, or potentially we can use this as an example in Ex 4 to link the materials together.

**Comment by JimCircadian** [comment]
Quite happy to raise a PR for this if of interest 😉

**Comment by bkmgit** [comment]
While useful, the lesson gradually introduces concepts and due to the time available, learning a few concepts well and practicing them several times is better than being introduced to many concepts without a chance to practice them sufficiently.  The suggestion https://github.com/swcarpentry/shell-novice/issues/1311 directs people to [the Linux Documentation Project](https://tldp.org/), where those who are interested will read the extra materials available.

**Comment by JimCircadian** [comment]
Reference to the TLDP issue would be #1312! 😉
