### ISSUE TITLE
Link to installation instructions points to a workshop template

### ISSUE THREAD

**Issue by emcaulay** [swcarpentry/shell-novice#1417]
Hello,

I'm preparing to teach this lesson next week and was reviewing it as part of my preparation. In Episode 1, in the section under the header "Install Software" there is a link to installation instructions that points to this address: https://carpentries.github.io/workshop-template/#shell. 

This is a confusing place to end up. It's a workshop template so it has the title "Fixme" and is disorienting. I'm not sure if this was something that needs attention after the Workbench transition. (I thought I remembered having a configuration and set up page for Software Carpentry in the past, but I may be misremembering.)

I'm sorry I can't be more helpful and actually make an edit to correct the problem. Happy to discuss anything or review solutions.

**Comment by bkmgit** [comment]
Thanks for reporting this. The instructions live at https://github.com/carpentries/workshop-template/blob/gh-pages/_includes/install_instructions/shell.html and are also used for Git lesson. Embedding them in the shell lesson directly is not great as it would not allow updates to be easily incorporated in the Git lesson or in the lesson setup template.  Would need to co-ordinate with Git lesson maintainers to change this. Is the wording in the [Git lesson](https://swcarpentry.github.io/git-novice/#installing-git) clearer, if so can use that for now?

**Comment by bkmgit** [comment]
@emcaulay Please also see
- https://github.com/carpentries/workshop-template/issues/801
- https://github.com/swcarpentry/git-novice/issues/936

**Comment by zkamvar** [comment]
This is something that has been discussed at length and the unfortunate reality is that we haven't had the capacity to work on this task: https://github.com/carpentries/maintainer-RFCs/issues/9

**Comment by tobyhodges** [comment]
Thanks @emcaulay for bringing this back up, and @bkmgit for suggesting a solution. As Benson mentioned, the idea is for us to have a set of install instructions that can be maintained in one place so that it is as easy as possible to keep them up-to-date. However, it is absolutely true that it is not ideal to be linking from lessons to instructions on a page with a lot of FIXMEs at the top.

I propose to create a new page on the `workshop-template` site that will contain only the setup instructions blocks. This would be populated by looping through all of the files stored in the `_includes/install_instructions/` directory. The resulting page could then be linked to from all of the Setup pages. I will be happy to open the pull requests to make those changes.

Any time the installation instructions need to be updated, the file in `_includes/install_instructions/` could be edited and the content it produces will be updated on both this centralised installation page and on the webpages of individual workshops created with the template repository.

**Comment by bkmgit** [comment]
@tobyhodges Thanks

**Comment by bkmgit** [comment]
@emcaulay Closing this. Please re-open if more is needed.
