### ISSUE TITLE
Explain why users should avoid white spaces in file name

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#170]
In `02-create.md`, will be good to have a call out box closer to "With Great Power Comes Great Responsibility" explaining why white spaces in file names are bad. For example

~~~
$ ls
bar  foo bar
$ rm foo bar
rm: cannot remove ‘foo’: No such file or directory
$ ls
foo bar
~~~

**Comment by ChristinaLK** [comment]
+1

**Comment by madkiwi23** [comment]
FYI - If they want white space then you just need to enclose it in quotes to access it.
e.g. 
[root@xxxxxxxxxxxx ~]# vi "wombat here"
[root@xxxxxxxxxxxx ~]# ls "wombat here"
wombat here
[root@xxxxxxxxxxxx ~]# rm "wombat here"
[root@xxxxxxxxxxxx ~]# ls "wombat here"
ls: cannot access wombat here: No such file or directory

But, it's not just white spaces that can cause issues.
Depending on the platform used other non-printable characters can be introduced that make it difficult to access a file or directory.
e.g. From an arts researcher, I have only left the "bad" part of the directory name (for privacy) in:
'/xxx/xxxxx/xxxxxxx/xxxxxxxxxxx/xxxxxxxxxx/2014 Big Wave Tauranga/xxxxxxxxxxxxxx/xxxxxxx.mov' 
Note the character following Tauranga---------------------------------^

This was created from a Mac on a Linux based share.
I have seen quite a few other occurrences of this on directories and files amongst other research files.
To access this directory (or any files with similar type charecters) you need to find the binary value of the character and use an escape \xxx to get at it.
Hence it is always best to use a "fixed" code, ansi or UTF-8, with UTF-8 being my preference as it is usable on all platforms. (*nix, Mac and Windoze) 
(This can also cause other problems, e.g. trying to back it up or restore it)

**Comment by steveholden** [comment]
Note also that filenames beginning with "-" are a perpetual cause of problems for beginners, since deleting them with the `rm` command is problematic: typically they are interpreted as options and flagged as invalid. So a warning and an explanation of how to deal with them (use the `--` option to indicate that following arguments are filenames) might be helpful.

Also any character with meaning to the shell ($, quotes, parens, etc.) should be avoided because of the difficulty of dealing with them in the shell.

**Comment by tomwright01** [comment]
Having just created a directory named `~` then attempted to delete it with
`rm -rf ~`

I can only +1 this.

**Comment by steveholden** [comment]
Ouch! Sorry for your (data) loss

**Comment by gdevenyi** [comment]
+1 for this

**Comment by jttkim** [comment]
At the risk of stating the obvious, the method for deleting (or otherwise manipulating) files with names starting with `-` or `~` is to expressly state the (current working) directory. E.g.
```
rm ./~
mv './-rf *' evil_file.txt
```
Technically, the `--` special argument to expressly demarcate the end of options is a feature of GNU getopt (as provided by glibc), as far as I know, so this isn't supported on all non-Linux systems (although glibc pretty much rules these days).

**Comment by steveholden** [comment]
I have to agree it's certainly best to teach the most general solutions - something that works on all platforms is to be preferred.

**Comment by steveholden** [comment]
How about this as an outline, at least:

* Yes, you can create files with spaces in their names, other people do it and you need to know how to handle them.
* Similar reasoning applies to avoiding characters in filenames that have specific meanings to the shell (the common punctuation).
* Explain simplest solutions to most common problems
* Explain that shell auto-complete is very useful in handling such names
Close by pointing out that because not everyone is as smart as they have (now) become they should be kind to the others and not use such characters in filenames.

**Comment by marcsze** [comment]
umich is going to give this one a shot.

**Comment by gdevenyi** [comment]
Some work already done here, https://github.com/swcarpentry/shell-novice/pull/383 please base on that and address my comments. Thanks~!

**Comment by marcsze** [comment]
will do!
