### ISSUE TITLE
Nano is not consistently present editor 

### ISSUE THREAD

**Issue by nahumj** [swcarpentry/shell-novice#220]
The default install for Windows machines (Git for Windows) doesn't include nano, so students have to use a heavier solution like Notepad++ to do simple file editing. We had to teach rudimentary vi to enable Windows users to keep up and not leave the terminal.

**Comment by rgaiacs** [comment]
> The default install for Windows machines (Git for Windows) doesn't include nano

That is true. Because of that we request that students install https://github.com/swcarpentry/windows-installer (that include nano and other things).

**Comment by petebachant** [comment]
From the new official Git Bash on Windows nano needs to be run with `winpty nano`. Even then, my arrow keys were not working as expected. Maybe request nano to be included with [Git for Windows](https://github.com/git-for-windows/git)?

In our workshop a few days ago Windows users used notepad (not notepad++), which could be opened from the shell without path modifications.

**Comment by petebachant** [comment]
Also reported to git-for-windows/git#334

**Comment by jduckles** [comment]
This was addressed by @ethanwhite in https://github.com/swcarpentry/workshop-template/pull/235 
> **Important: on the 6th page of the installation wizard (the page titled `Configuring the terminal emulator...`) select `Use Windows' default console window`.

**Comment by ChristinaLK** [comment]
`notepad` has always worked on Windows (for me) if the `nano` install was botched.  Someone (me), could add a note to `instructors.md` to that effect (or possibly 02-create)?

**Comment by jttkim** [comment]
One snag with notepad on Windows is that it doesn't recognise anything other than CRLF as the line separator ("Windows style"). So if you run `notepad nelle/notes.txt`, you get the entire file in one line.

It's worth noting as a big plus that notepad works from the command line at all, though. Therefore, it integrates into the workflow of navigating to the relevant directory and doing your work there, rather than requiring students to synchro-navigate in their shell and the fileselect box of their GUI editor.

**Comment by madkiwi23** [comment]
This may be "out of scope" but if you have windows users I would suggest notepad++, there is a free version. I use it because I have to edit both *nix and windows text files on a windoze platform. 
It has a myriad of options but out of the box the only 2 to worry about is EOL (windows or unix) and possible character set to use for new files. I always set character set to UTF-8 then EOL conversion to whichever platform the file is destined for, windoze or unix. 
Note: I work at a University so this is not a plug for the product! 8)

**Comment by gdevenyi** [comment]
The existing installer handles this. #233 and #235 will resolve this to inform instructors.
