### ISSUE TITLE
Red dragon is missing

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#224]
At https://swcarpentry.github.io/shell-novice/04-loop.html there is a call out box named "Spaces in Names" that mention one file named `red dragon.dat` that is not present at https://github.com/swcarpentry/shell-novice/tree/gh-pages/data/Users/nelle/creatures. I think that we could have the file `red dragon.dat`.

**Comment by iglpdc** [comment]
I think the file is not supposed to be there. The call out box says "Suppose we have this file ...". I think it would be best if the instructor creates the file at the end (or at some point) of the lesson to explain the problems of having a filename with whitespaces, because the first part of the lesson assumes that you only have `unicorn.dat` and `basilik.dat`.

**Comment by ChristinaLK** [comment]
I agree with @iglpdc - the `red dragon.dat` file is described for illustration purposes, but otherwise isn't part of the lesson.
