### ISSUE TITLE
man command not found on git bash

### ISSUE THREAD

**Issue by emilydolson** [swcarpentry/shell-novice#249]
man doesn't seem to be installed on git bash - learners get a "man: command not found" error when they try to use it.

**Comment by jiffyclub** [comment]
Yup, no `man` with Git Bash. I try to remember to note this for students and tell them about `<command> --help` instead.

**Comment by emilydolson** [comment]
Ah, okay. So there's no fix?

**Comment by jiffyclub** [comment]
Not that I know of.

**Comment by elliotpryde** [comment]
As a workaround, I've installed [TLDR pages](https://tldr.sh/) and set it as the default keyword search tool with `:set keywordprg=tldr`.

**Comment by ThornWinters** [comment]
I add this to my .bash_profile
`man(){
  $1 --help
}`

**Comment by BJWiley233** [comment]
adding this below does not work in windows.  should it?
`man(){ $1 --help }`

**Comment by AlexStefanov2** [comment]
There's no `gets --help` but there's `man gets`. Man is more than just help for your bash commands

**Comment by rgaiacs** [comment]
> Does anyone know a way to manually install `man` pages into git bash?

Not out of the box. If you really need `man` you might want to install https://www.cygwin.com/.

**Comment by AmanL04** [comment]
> As a workaround, I've installed [TLDR pages](https://tldr.sh/) and set it as the default keyword search tool with `:set keywordprg=tldr`. Thought I'd add my solution here since this is one of the first google results.

Hey thanks man. This worked like a charm.

**Comment by ernstki** [comment]
It's also possible to use the regular [MSYS2 installer](https://www.msys2.org/), install `git`, `nano`, and `man-pages-posix` using `pacman`, and you'll have roughly the same setup as Git for Windows (which is based on MSYS2 anyway), except you'll have man pages.

```bash
pacman -S git nano man-pages-posix
```

If you're using Git a lot and don't like typing in passwords to push and pull from remotes, this is a minor step backward, because you _probably_ won't get the Git for Windows credential manager, or its integration with your system certificate store.

**Comment by Irfan434** [comment]
Use --help. If you keep typing `man` out of habit, like me, paste this into the shell:
```
cat << EOF >> ~/.bashrc
myMan(){
        \$1 --help | less
}

# if man command not found, alias to myMan
man 2>/dev/null
if [ \$? -eq 127 ]
then
        alias man=myMan
fi
EOF
```

**Comment by ernstki** [comment]
A lot of these solutions are clever, but, if we're being honest with ourselves, they aren't going to help the "learners," as the original issue states, because the root of the problem is that Git Bash is not "real Unix."

@elliotpryde's suggestion is great, but honestly which student just going through these course materials for the first time is going to be using Vim, know that you can do man page lookups within it (with <kbd>K</kbd> in normal mode), or even _recognize_ that that magic command needs to go in your `~/.vimrc`? (Eliot, you might want to update your comment to make that clear...)

And that's sad, because man pages are one of the great things about a Unix environment, and it's a shame to have to go, "oh, psych, that doesn't work for you, because you have Git Bash," to which the inevitable response is "What's Git? I thought this was Unix?"

The Software Carpentry course materials _do_, if I recall, mention that you might need to use `--help` instead on Windows, and it might even suggest using an online reference like <linux.die.net>, but as @umnikos points out, that's not a proper substitute for being able to do `man command` right in the shell. At all.

Thing is, Git Bash is still the best thing going on Windows, for first-time learners, because MSYS2 and Cygwin are not complete solutions unless you know which packages to install. So I think I'll try to raise the issue with the Git Bash folks and see what they say. I'll report back. `;)`

**Comment by swaldman3** [comment]
This is gonna become moot in a couple of years - once Windows 7 leaves supported status, and hence everybody is hopefully on 10, there's no longer a reason to use git bash rather than Win10's built-in Ubuntu support :-)

**Comment by ernstki** [comment]
@swaldman3 Does this feature really _ship_ with Windows 10 though? As of this writing, it looks like you have to sign up for some "Windows Insider" program to get access, probably have to wait for an update to download, then find the "developer mode" switch buried in the control panel and [switch that on](https://www.wikihow.com/Enable-the-Windows-Subsystem-for-Linux). And of course reboot. Also, who knows whether the "Home" version of Windows 10 will even have this capability.

For workshops, maybe still not as straightforward as "here, download this free program from this web site (no signup required) and install it, then click on this icon in the Start menu."

**Comment by swaldman3** [comment]
Yes, it really ships with Windows 10, including Home editions. Has done for a couple of years now. You don't have to sign up for anything. You do have to enable the "Windows subsystem for linux", and then install your chosen distro through the Microsoft Store, but these are not substantially harder to follow instructions for than installing git bash - there are probably fewer options to choose - and then you end up with a (to our intents and purposes) fully functional linux distro and none of the usual weirdnesses of no man, different line endings, etc.

**Comment by ernstki** [comment]
Ah. Well I'll be. What version of the universe do we live in where this is really possible? It's a far cry from the Steve Ballmer days, anyway. <tt>;)</tt>

**Comment by AustinTSchaffer** [comment]
@swaldman3

> then you end up with a (to our intents and purposes) fully functional linux distro and none of the usual weirdnesses of no man, different line endings, etc.

I'm still waiting for MS to mainline WSL2 before I suggest people try out WSL. With WSL you get to actually live in a *nix environment which eliminates some weirdness, but WSL(1) has its own weirdness regarding significantly slower file system IO, due to how it was implemented.

https://github.com/microsoft/WSL/issues/981

https://github.com/microsoft/WSL/issues/873

**Comment by Kimber720** [comment]
As mentioned before...this does NOT in any way help a total newbie trying to get through learning at a camp on a MS product.

**Comment by ernstki** [comment]
Just to follow up on something I said I'd check into: It seems unlikely that [Git for Windows](https://gitforwindows.org/) (which provides Git Bash) will ever include the manual pages, based on the discussion in git-for-windows/git#696.

I don't think it's a _completely_ foregone conclusion, I just think that the maintainer himself doesn't see it as a priority, so it's unlikely to happen unless somebody (me?) does it for him and submits a pull request.

**Comment by ajanac** [comment]
command_name --help worked for me 👍

**Comment by hanisntsolo** [comment]
> Yup, no `man` with Git Bash. I try to remember to note this for students and tell them about `<command> --help` instead.

Thank you so much, brother

**Comment by PantheraRed** [comment]
I'm pretty sure you can simply install `man` by typing `apt install man` in terminal (ubuntu).

**Comment by swaldman3** [comment]
> 
> 
> I'm pretty sure you can simply install `man` by typing `apt install man` in terminal (ubuntu).

git bash is something used by classes to have a limited linux shell, and CLI access to git, in *windows*.

**Comment by Kolotokon** [comment]
Эта команда в Git Bach ответить на ваш вопрос ! Какой командой можно посмотреть параметры и ключи в git bash .
$ ls --help
