### ISSUE TITLE
Bug in the command tail in the first exercise (Variables in shell scripts) of the lesson 6 (Shell Scripts)

### ISSUE THREAD

**Issue by chunggnuhc** [swcarpentry/shell-novice#308]
The exercise ask about the shell script containing the following commands:

````
head $2 $1 
tail $3 $1
````
But the second command has a bug on the syntax.
It is a little [obscure](http://lists.gnu.org/archive/html/bug-coreutils/2011-03/msg00074.html). And to fix it, the command should be 

````
bash script.sh '*.pdb' -1 -n1
````

**Comment by rgaiacs** [comment]
`tail -1 *.pdb` works for me with GNU bash, version 4.3.42.

**Comment by abelsiqueira** [comment]
`tail -1` is no longer supported, though some systems accept it.
GNU bash version 4.3.42(1)-release with GNU coreutils tail 8.24.

Not much talk around this because they believe is explained well enough (the link @chunggnuhc gave). But [it happens in other places too](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=63269).

**Comment by shwina** [comment]
Are the forms `head -n $N` and `tail -n $N` more suitable? If so, do we want to use those forms throughout the lesson?

**Comment by abelsiqueira** [comment]
These forms are supposed to be the correct ones, for GNU tail. I don't know what Windows and OSX use though.
I believe they should be used throughout the lesson.

**Comment by ChristinaLK** [comment]
agree w/ @abelsiqueira - I know that tail -1 works, but tail -n 1 is the more "correct" (and fully supported version).
