### ISSUE TITLE
Improve answer to Exploring More ls Arguments

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#477]
Question:

> What does the command ls do when used with the -l and -h arguments?

Current Solution:

> The -l arguments makes ls use a long listing format, showing not only the file/directory names but also additional information such as the file size and the time of its last modification. The -h argument makes the file size “human readable”, i.e. display something like 5.3K instead of 5369.

Suggest Solution:

> For `-l` we will have something like
>
> ~~~
> drwxr-xr-x 2 raniere raniere  4096 Oct 12 14:41 creatures/
> drwxr-xr-x 4 raniere raniere  4096 Oct 12 14:41 data/
> drwxr-xr-x 2 raniere raniere  4096 Oct 12 14:41 Desktop/
> drwxr-xr-x 2 raniere raniere  4096 Oct 12 14:41 molecules/
> drwxr-xr-x 3 raniere raniere  4096 Oct 12 14:41 north-pacific-gyre/
> -rw-r--r-- 1 raniere raniere    86 Oct 12 14:41 notes.txt
> -rw-r--r-- 1 raniere raniere    32 Oct 12 14:41 pizza.cfg
> -rw-r--r-- 1 raniere raniere 21583 Oct 12 14:41 solar.pdf
> drwxr-xr-x 6 raniere raniere  4096 Oct 12 14:41 writing/
> ~~~
> 
> The first 10 characters represent permission. `d` means ... The first number is ... The first name is the group owner of the file and the second name is the user owner of the file. ...

**Comment by shwina** [comment]
@rgaiacs What do you think about removing `-l` entirely from the lesson?

**Comment by GiorgiaMori** [comment]
Hi @rgaiacs @shwina,

The -l flag is nicely explained in a Data Carpentry episode: [Working with Files and Directories](https://datacarpentry.org/shell-genomics/03-working-with-files/index.html) - Introduction to the Command Line for Genomics Lesson.

It would be nice to introduce something similar in the [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir/index.html) Software Carpentry Episode.

Here is an example:


### File Permissions

File permission controls if the user that ran the ls command can access files in UNIX systems. 
You will need to check/change file permissions before trying to write files into a directory (we will talk about this in a later lesson) in which you do not have write permission. UNIX permissions are also called *rights*.

View the current permissions on a file using the `-l` (long) flag for the `ls` command: 

~~~
$ ls -l
~~~
**Output:**
~~~
-rw-r--r-- 1 scuser scuser 43332 Sep 21 22:02 myfile.txt
~~~

The first part of the output for the `-l` flag gives you information about the file's current permissions. There are ten slots in the
permissions list. The first character in this list is related to file type, not permissions, so we'll ignore it for now. The next three
characters relate to the permissions that the file owner has, the next three relate to the permissions for group members, and the final three characters specify what other users outside of your group can do with the file. We're going to concentrate on two positions that deal with your permissions (as the file owner). 

![image](https://user-images.githubusercontent.com/54341266/93767424-59f9fb80-fc5b-11ea-9f77-9da4c15c8d16.png)

The three positions that relate to the file owner are `rw-`, and we are going to focus on the `r` and the `w` . The `r` means that you have permission to read the file, the `w` indicates that you have permission to write to (i.e. make changes to) the file. 

Our goal for now is to change permissions on this file so that you no longer have `w` or write permissions. We can do this using the `chmod` (change mode) command and subtracting (`-`) the write permission `-w`. 

~~~
$ chmod -w myfile.txt
$ ls -l 
~~~
**Output:**
~~~
-r--r--r-- 1 scuser scuser 43332 Sep 21 22:02 myfile.txt
~~~

Likewise, if we want to change permissions again and add again write permission, we can do this by using `+` before the write permission `-w`. 

~~~
$ chmod +w myfile.txt
$ ls -l 
~~~
**Output:**
~~~
-rw-r--r-- 1 scuser scuser 43332 Nov 15 23:02 myfile.txt
~~~


Would it be worth also adding an exercise about it?

**Comment by gdevenyi** [comment]
Hi,

At the current time, shell-novice doesn't have any more space available to add additional content. In addition, given the goals of the lesson, permissions are outside of the scope of the novice introduction for the purposes of getting computational work done on the shell.

The shell-extras repo has a lesson on permissions, and we would welcome additions/improvements to it
https://github.com/carpentries-incubator/shell-extras/blob/gh-pages/_episodes/04-permissions.md

Thanks!
