### ISSUE TITLE
examples of "orthogonality" questionable

### ISSUE THREAD

**Issue by delocalizer** [swcarpentry/shell-novice#541]
@gvwilson  A quibble - I don't believe that the examples of `.` and `..` [given here in lesson 2](https://github.com/swcarpentry/shell-novice/blame/8a135d15821510648314f90183ef7e650a04e0f0/_episodes/02-filedir.md#L578) and wildcard expansion [given later in lesson 4](https://github.com/swcarpentry/shell-novice/blame/e2f1725fe47172e5779f9ae1a7af3adda75fa1d8/_episodes/04-pipefilter.md#L98) are really examples of orthogonal design;  `.` and `..` are simply conveniences provided by the filesystem, and wildcards are a convenience provided by the shell. Orthogonal design is design for composability and lack of side-effects. I think the line "[they are interpreted the same way by every program](https://github.com/swcarpentry/shell-novice/blame/8a135d15821510648314f90183ef7e650a04e0f0/_episodes/02-filedir.md#L579)" is particularly problematic because it might imply that if you were to write a new program, you should handle `.` and `..` or `*` and `?` specially in your cli args, to maintain "orthogonal design". If you want to introduce the concept of orthogonality I believe it would be better off in the lesson on pipes, with the example of coreutils (mostly) being designed to use stdin and stdout streams in the same way, allowing pluggable combinations of things.

**Comment by navjotk** [comment]
I agree with this thought. This is exactly what I thought when I was going through the lessons - that `.`/`..` and wildcards aren't very good examples of orthogonality - STDIN/STDOUT are better examples.

**Comment by jttkim** [comment]
Technical `.` and `..` can be used in the same way with all programs because they're all coded using the same API / libraries to access files by name. So the the statement that "they are interpreted in the same way by every program" is correct, and the consistency of interpretation comes from using the same mechanism of interpretation, so this is orthogonality -- the libraries are an orthogonal component that is factored out from almost all programs.

Explaining this technical background is probably too distracting / difficult for this lesson, and without more explanation the "interpreted the same way by every program" phrase can indeed leave novices with a misconception that consistent interpretation is achieved by code duplication.

A solution might be to keep focus on the user level at this point, and replace "hey are interpreted the same way by every program" with "you can use these elements with all programs".

**Comment by deppen8** [comment]
This is an old issue, but I would support removing the reference to orthogonal design patterns.

I would support keeping lines 521-525 and maybe inserting it at line 503. Adding some labels for visibility.
