### ISSUE TITLE
`ls --help` step should be made more compatible (`illegal option` in MacOS)

### ISSUE THREAD

**Issue by seanmatheny** [swcarpentry/shell-novice#543]
In "Navigating Files and Directories", the command `ls --help` when run on MacOS systems yields the error: `ls: illegal option --`. I realise that if we make accomodations for syntax for every single *nix variant, the lesson will quickly lose its simplicity and flow. However when I taught this lesson, around 50% of the class had Macs and were following along with the shell, so this little difference affects a large percentage of people. Another reason why I think this should be fixed is the position in the lesson. `ls --help` is the fifth command the students type in; I think commands should be completely compatible at the beginning to build confidence. If the very command that gives them help when they're stuck won't work for them, it doesn't build much confidence. 

When I taught this lesson recently, I needed to explain why there were differences between *nix commands and syntaxes; I fielded a couple questions on this, and it seemed like the wrong point in the lesson to introduce complexity.

**Comment by alee** [comment]
I just encountered this myself last Wednesday during my training checkout demo with a base shell environment with the default MacOS BSD `/bin/ls` instead of my customary MacPorts GNU coreutils ls. 

Maybe a simple fix would be to use `man ls` in that particular example and let the students know they can find more information about a command via `man` or `--help`, and to try one or the other?

**Comment by rgaiacs** [comment]
[GNU Core Utils](https://en.wikipedia.org/wiki/GNU_Core_Utilities) and BSD Base System aren't 100% compatible. :-( And not all utilities are consistent. (T_T) Some will have `--help` or `-h` or none. `man` is probably the only thing that will work for both **but** Git Bash doesn't include `man`. :-( We are discussing moving to [Cygwin](https://github.com/carpentries/conversations/issues/11) which will solve the problem of "`man` not found".

Please hold any fix to this issue until we make a decision to move to Cygwin or not.

**Comment by ErinBecker** [comment]
Glad I found this issue to understand the history behind this problem. @rgaiacs I understand that we're discussing a move to Cygwin, which will affect how this problem is resolved, however it seems to me that, even if the solution we're able to make is only temporary, we should in fact implement some fix.

To a new instructor, this section of the lesson is very confusing. First, learners are instructed to use `ls --help`, which for many of them will give an `invalid option` error. The next thing that is discussed in the lesson is how you can get this error if you use an option that is not supported. It then introduces the `man` command, and states that `man` isn't supported by Git for Windows. 

Couldn't it simply say something to the effect of "If you're using a Mac or Linux system, use `man ls`, if you're on Windows, use `ls --help`? We can always update these directions later, but as is right now they are very confusing to new instructors and to learners.

**Comment by ErinBecker** [comment]
Also just saw #447, with more information about this issue. It appears that there's been some trouble with this since at least September 2016.

**Comment by HadrienG** [comment]
Just encountered this preparing for my instructor training. I agree with @ErinBecker , introducing `man ls` and `ls --help` at the same time fixes the problem.

**Comment by shwina** [comment]
PR welcome for including both `man` and `--help`

**Comment by rgaiacs** [comment]
Can we just say "Google 'man ls'"? It will solve the problem.

**Comment by marwahaha** [comment]
We should really direct novice instructors to pages like these -- I feel like issues like this become tribal knowledge, which is bad. It should be in the lesson, and ideally the lesson would update with these fixes relatively quickly. 

Of course, this is volunteer-based and things take time (totally okay!) -- but flagging that I'm only comfortable navigating this section of the lesson is because I've seen it before. This is super early on the first day in the first session; IMO, the bug has potential to derail or demotivate the instructor.

**Comment by MattForshaw** [comment]
Hi Everyone,

I am working on a fix for this for my students (who are all on macOS) but I can easily extend this out to cater for other OSes.

Would a PR be welcome to address this, and would this be the best issue to reference against the issue?

Best wishes,
Matt

**Comment by shwina** [comment]
@MattForshaw yes please. Thanks!

**Comment by massich** [comment]
We are at the swctraining at Scipy 2018, I was doing my 3' lecture-demo and I run into trouble the second time I did the demo 'cos the colleagues for the second round  where using mac and I was chocked that `ls --help` didn't work and that was pretty much the end of the demo.

Shall we put a banner on the documentation or similar?
