### ISSUE TITLE
Recommendation to Instructors about man because it doesn't work in Windows

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/shell-novice#55]
Windows doesn't have `man` installed. To improve the experience of our students that use Windows machines we could make a few changes in the write version of our shell lessons.

- [ ] Add call out to mention `man` and warning Windows users, see https://github.com/swcarpentry/shell-novice/issues/55#issuecomment-71153553.
- [ ] Add note at `instructors.md`, see https://github.com/swcarpentry/shell-novice/issues/55#issuecomment-71153553.

**Comment by wking** [comment]
On Wed, Jan 21, 2015 at 06:22:55PM -0800, Raniere Silva wrote:
> Windows doesn't have `man` installed. To improve the experience of
> our students that use Windows machines we should use `command
> --help` instead of `man command` and make a few changes in the write
> version of our shell lesson.
>
> - [ ] In `06-find.md`, replace `man grep` with `grep --help`.

Ugh.  Can't we just suggest they use the web to get the man page?
E.g. [1].  We may be able to script that up in a little man stub using
Python's webbrowser [2] and install the script using our Windows
installer.  For Git, it doesn't matter if you use ‘man’ or ‘--help’,
but on my system grep(1) is 649 lines of useful explanation (e.g. it
talks about character classes, bracket expressions, regexp anchoring,
…) and ‘grep --help’ is 76 lines of compact usage information.

[1]: http://unixhelp.ed.ac.uk/CGI/man-cgi?grep
[2]: https://docs.python.org/3/library/webbrowser.html

**Comment by r-gaia-cs** [comment]
> Can't we just suggest they use the web to get the man page?

I'm OK with using the web. This is just a suggestion that @dbarneche gave me.

**Comment by gvwilson** [comment]
Learners frequently can't get on wireless during workshops, either 
because they're from a different institution, or because university 
wireless can't handle the load, or just because.  We should therefore 
tell people about both `man` and google.

**Comment by wking** [comment]
On Thu, Jan 22, 2015 at 04:57:54AM -0800, Greg Wilson wrote:
> Learners frequently can't get on wireless during workshops, either
> because they're from a different institution, or because university
> wireless can't handle the load, or just because.  We should
> therefore tell people about both `man` and google.

So I'd tell leaners:

1. Use ‘man’ if you have it, since it's easy to run and gives detailed
   advice.  If you don't have it, fall back to…
2. A man page (or other docs if you can find them) posted online.
   More work to find, but you get man-page-quality advice.  If you
   don't have network access or can't find the appropriate docs, fall
   back to…
3. ‘--help’, which will usualy get you the command syntax.  That may
   be enough to jog your memory.  If you're lucky (e.g for Git), the
   --help will be as useful (or exactly the same as ;) the man page
   ;).

And I'd leave it up to instructors to gloss over any bits they felt
weren't pertinent to their class (e.g. don't mention ‘man’ if all your
students are Windows users who are masochistically learning about the
POSIX shell ;).

**Comment by r-gaia-cs** [comment]
I updated the description of this issue since I believe that we could agree with @wking's last comment.

**Comment by ChristinaLK** [comment]
This is also referenced in (old) PR #24.

**Comment by JohnRMoreau** [comment]
Should we add a link to the GNU Bash site man page? [https://www.gnu.org/software/bash/manual/](https://www.gnu.org/software/bash/manual/)
We might want to add this link to either the shell lessons, the instructor notes, or the workshop template.

**Comment by gdevenyi** [comment]
Yes please, PR's welcome :)

**Comment by gdevenyi** [comment]
Resolved.
