### ISSUE TITLE
Various fixes - submitted by email for instructor training

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#593]
http://swcarpentry.github.io/shell-novice/02-filedir/
Unsupported comand-line options
--> command mis-spelled

http://swcarpentry.github.io/shell-novice/04-pipefilter/
The output is 1520 lines that look like this:
--> "1,520"

http://swcarpentry.github.io/shell-novice/04-pipefilter/
Nelle has run her samples through the assay machines and created 1520 files in the north-pacific-gyre/2012-07-03 directory described earlier. As a quick sanity check, starting from her home directory, Nelle types:
--> Non-trivial:  Worth defining that an "assay" machine checks metal ore for its integrity of ingredients and quality.

http://swcarpentry.github.io/shell-novice/07-find/
Here, not is the pattern we’re searching for. The grep command searches through the file, looking for matches to the pattern specified. To use it type grep, then the pattern we’re searching for and finally the name of the file (or files) we’re searching in.
--> type "grep" ; put grep in quotes

**Comment by gdevenyi** [comment]
PRs welcome.

**Comment by reshama** [comment]
@ErinBecker @gdevenyi **PR submitted**
file: http://swcarpentry.github.io/shell-novice/02-filedir/
PR:  https://github.com/swcarpentry/shell-novice/pull/603

**Comment by colinmorris** [comment]
I think this can be closed now. Going down the list...

> --> command mis-spelled

Fixed in #603. Thanks!

> --> "1,520"

Current lesson version uses a different number.

> --> Non-trivial: Worth defining that an "assay" machine checks metal ore for its integrity of ingredients and quality.

This is interesting, but I don't think it necessarily helps a reader understand the code/examples in this section, so I'd say it's out of scope. (But happy to continue this discussion if you disagree.)

> --> type "grep" ; put grep in quotes

In the current version, `grep` is in backticks (to give it monospaced/code formatting), which I think is consistent with the formatting in the rest of the lesson.
