### ISSUE TITLE
Cover how to exit VI/VIM

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#607]
Original submitted to instructor training repo. Please see discussion here: https://github.com/swcarpentry/instructor-training/issues/487

**Comment by souravsingh** [comment]
@ErinBecker I am interested in covering this. Do I need to add a new section?

**Comment by ErinBecker** [comment]
Thanks @souravsingh! I think this might be best in a callout. Any thoughts from the maintainers?

**Comment by gcapes** [comment]
Yes, a callout would be ideal if this is going to be covered. As always, what would you take out to make room for it?

However, the lesson doesn't cover using vi, so you could argue it isn't that useful covering how to exit from vi. You might equally argue, why don't we cover how to exit emacs?

**Comment by vai2fc** [comment]
For what it's worth, a callout (like the one in [Git Novice lesson 2](http://swcarpentry.github.io/git-novice/02-setup/#exiting-vim)) could help those using the tutorial to teach themselves from getting stuck in a Vim loop.

**Comment by jttkim** [comment]
@gdevenyi it also happens in rather numerous other situations when `EDITOR` is unspecified (or, in fact, set to `vi`). I've seen it happen, my gut feeling is it's more frequent when learners are using a Linux box (but that may be because it happens to me on Linux boxes only). It may not happen if a learner sticks strictly to the lesson, but googling something and trying that out is all it takes to possibly end up in `vi` without particularly bargaining for that. Also, being aware of the existence of `vi` and having some minimal ability to handle encounters with that will help learners as they independently continue using the shell after the workshop, even if they don't have any such encounter during the shell lesson.

On this occasion, for what it's worth I have once up on a time written this simple `vi` tutorial: http://jtkim.dreamhosters.com/vi_minitut.html , please feel free to use this in whichever way it may be useful

**Comment by iglpdc** [comment]
I agrre with @gdevenyi. And as, @vai2fc says above, we cover this, and also how to select an editor, in the Git lesson. Maybe a link to that callout can help.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup. If there is still appetite for this change, we can reopen.
