### ISSUE TITLE
ls -F needs more explanation

### ISSUE THREAD

**Issue by weisi-chen** [swcarpentry/shell-novice#644]
ls -F (more explanation on why use -F is needed)

**Comment by gcapes** [comment]
I'd say it's fine as it is. Have you seen this (from episode 2)?
> ls prints the names of the files and directories in the current directory in alphabetical order, arranged neatly into columns. We can make its output more comprehensible by using the flag -F (also known as a switch or an option) , which tells ls to add a trailing / to the names of directories:

**Comment by colinmorris** [comment]
One thing that might make this a little confusing is that, in the example shown in the lesson, the pwd contains *only* directories. 

```
Applications/ Documents/    Library/      Music/        Public/
Desktop/      Downloads/    Movies/       Pictures/
```

If there were one or two files in there, it might make the usefulness of `-F` clearer (it lets you distinguish between directories and files at a glance):

```
Applications/ Documents/    Library/      mongoose.jpg    Music/    Public/ 
Desktop/      Downloads/    Movies/       Pictures/       Todo
```

**Comment by Lyndon18** [comment]
It may also be useful to introduce flags formally, before adding flags into the examples.

**Comment by loz-hurst** [comment]
Should it be clarified that '-F' is a general 'classify' flag - i.e. it does not *just* add '/' to directories (which is the implication of the lesson text) but also adds characters to other 'special' files (e.g. '*' to executable, '@' to symlinks, '=' to sockets, '|' to pipes etc.).

I'm not suggesting introducing all these concepts, just describing '-F' as an option that classifies files rather than 'adds / to directores' which could be mis-leading.

**Comment by raynamharris** [comment]
I agree. This came up during my maintainer on-boarding class. I learned that it is really a quite useful tool for folks who don't use color coding. 

Also, I find the `ls -F` option quite useful option when combined with `-a` because it makes it more obvious that `./` and `../` refer to directories but agree with the folks above that it is unclear when the said directory contains only subdirectories.

**Comment by gshamov** [comment]
These days, colour terminals show files, directories and links in colour. Isn't ls -F often redundant? (I have seen it first time in the lesson myself.) Would it be more natural to introduce options to ls by using options that are used most often (ls -la, ls -lrt)?

**Comment by loz-hurst** [comment]
> These days, colour terminals show files, directories and links in colour. Many Linux distros actually alias ls to alias ls='ls --color=auto'

They're shown in colour if the non-default colour option is used.  It really irritates me that several distributions alias things to include non-default options so the same tool (as in the same version of the same project) behaves differently.  But, as we've already discussed, we want to stay clear of any discussion of the nuances of different distributions.  Quite how this all plays out with the other tools that have more significant differences between GNU and BSD implementations, I'm not sure.

**Comment by deppen8** [comment]
Closing as part of old issue cleanup.
