### ISSUE TITLE
lesson cannot be rendered locally

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/shell-novice#676]
I just did a fresh fork and clone of this repository and am not able to render it locally with jekyll. The problem appears to be that the all_figures.html file is not in _includes/. 

~~~
Erins-MacBook-Air-2:shell-novice ebecker$ jekyll serve
Configuration file: /Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice/_config.yml
            Source: /Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice
       Destination: /Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Could not locate the included file 'all_figures.html' in any of ["/Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice/_extras/figures.md
jekyll 3.6.2 | Error:  Could not locate the included file 'all_figures.html' in any of ["/Users/ebecker/Box Sync/Carpentry_repos/swcarpentry-lessons/shell-novice/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
~~~
{: .bash}

**Comment by rgaiacs** [comment]
This is due the latest version of the template. I sent #678 to fix this. Is pending merge.

We are now using (client side) Javascript because it will remove the requirement from maintainers to run the script to update `all_figures.html`. (Client side) Javascript is "evil" for learners that only have access to slow connection (or based in the US after the end of net neutrality) but because is only one page that we don't use very often this is less "evil" than having a inaccurate page.

Because `_extras/figures.md` is created by `bin/lesson_initialize.py` which would re-write some files that it shouldn't I had to left for maintainers to copy and past the file. And my instructions probably missed that step.
