### ISSUE TITLE
Shell customisation

### ISSUE THREAD

**Issue by richyvk** [swcarpentry/shell-novice#682]
I did my instructor teaching demo today. I number of us had customised our shells with colours, custom prompt etc.

It was pointed out that this is perhaps not a good idea, as it might confuse students who only have out of the box shell.

Rather, I thought it would be good to suggest that an episode could be added to this lesson covering customising your shell.  I think there can be a lot of benefit having colors to differentiate between folders & files, etc.

Could cover aliases to commands too. e.g. I alias `ls -F` to `ls`

**Comment by gdevenyi** [comment]
Hi @richyvk 
I think that shell customization is well outside of the shell-novice material, perhaps https://github.com/swcarpentry/shell-extras would be a better home.

I would be amenable to a small callout box in the initial sections covering "why is my prompt different than the instructor's?"

Otherwise, we suggest that instructors disable this "customizations" as to not overload the learners with "differences"

**Comment by richyvk** [comment]
@gdevenyi Thanks for the response. Fair comment. I guess I was thinking about making the shell as fun as it can be. To my mind it might be that people would use it more with some basic customisations - like colours. But sounds like that is out of scope for the lesson.

I see shell extras is not really complete. I'm guessing that means it doesn't get much use currently?

I might do a PR for a call out box perhaps. Or maybe I will do something with shell extras then?

**Comment by gdevenyi** [comment]
shell-extras is the place where good ideas like yours go :) Its a place to send learners who are keen to get more out of bash. It is not often "used" as a direct lesson, but it does happen.

Either or both contributions are welcome :)

**Comment by gdevenyi** [comment]
Thanks!
