### ISSUE TITLE
Appending Data Example in 04-pipefilter.md

### ISSUE THREAD

**Issue by gonzalezvl** [swcarpentry/shell-novice#706]
The example for "Appending Data" in 04-pipefilter.md on line 241. This practice solution introduces pipes and commands 'head' and 'tail', before the explanation/presentation of those commands in the lesson, it might be best if moved after the presentation of those commands.

**Comment by colinmorris** [comment]
That's a good point. I'm also a bit leery of the `-3` and `-2` flags, because:

1. We use the `-n` flag elsewhere in the lesson, and I'm not sure there's much value in teaching them two ways of doing the same thing in this case.
2. I'm not sure how portable they are, since they're not defined in POSIX
3. If we're introducing new flags and expecting them to know how they work, we should probably at least drop a hint about checking the `man` page.

**Comment by gdevenyi** [comment]
Looks like this is a casualty of moving exercises into the text from the end. We should consider moving it down or back to the bottom.

@colinmorris I agree on the -3 and -2. I'm going to open another issue regarding POSIXness, I think we've been bitten by this before. There are tools to help here.

**Comment by gcapes** [comment]
How about moving it after `Redirecting to the same file` callout? 
The good: 
- `head` has now been introduced
- it's still fairly close to where redirection is first mentioned

The bad: 
- `tail` hasn't been introduced (but I could quickly explain it in the exercise)

Alternatively, it could be moved to the end of the episode, but then we're asking learners to keep new information in their heads longer before solidifying it with an exercise.

Thoughts before I submit a PR? My vote would be to move it down rather than to the end.

**Comment by gcapes** [comment]
I'll submit a PR now I've made the changes - I can always amend it if required.
