### ISSUE TITLE
'$ls --help' 02-filedir.md

### ISSUE THREAD

**Issue by gonzalezvl** [swcarpentry/shell-novice#707]
Line 246 of 02-filedir.md, the command: "$ ls --help" does not produce output to match the lesson on  NATIVE MAC (OS 10.12.6) 'ls' ; as it does in the linux version. Can only retrieve 'ls' flag options through the man page. 

On native mac, the command produces this output:
$ ls --help
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]

**Comment by colinmorris** [comment]
This is indeed something that causes a lot of pain. There's already a issue on this topic, #543 (it's old enough to not be on the first page of issues, so I don't blame you for missing it). That one has a fair bit of discussion, so I'd like to keep it as the canonical issue for this.

For what it's worth, it sounds like #690 fixes this problem, but it's taking some time to go through review because of the scope of the changes it makes.
