### ISSUE TITLE
Unix shell Loops 'Spaces in Names' section

### ISSUE THREAD

**Issue by marisalim** [swcarpentry/shell-novice#712]
In the example for loops with file names that have spaces, the result without quotes around $filename, will actually return a result for unicorn.dat since that is one of the files in the SWC creatures/ directory. The output should look like this:

for filename in "red dragon.dat" "purple unicorn.dat"; do head -n 5 $filename; done
head: cannot open ‘red’ for reading: No such file or directory
head: cannot open ‘dragon.dat’ for reading: No such file or directory
head: cannot open ‘purple’ for reading: No such file or directory
==> unicorn.dat <==
COMMON NAME: unicorn
CLASSIFICATION: equus monoceros
UPDATED: 1738-11-24
AGCCGGGTCG
CTTTACCTTA

**Comment by jttkim** [comment]
It appears to me that the scenario "Suppose our data files are named: `red dragon.dat`, `purple unicorn.dat`" was written somewhat independently of the lesson, so the assumption is that the working directory contains only those two files. But if a learner actually tries the loop in the directory of the lesson, they'd see the result you describe -- so good catch.

Perhaps a solution is to rewrite this part as something like "Suppose you have a directory with the data files `amber anteater.dat` and `brown bear.dat`", i.e. (1) so that it's clear that this part does not pertain to the directory of the lesson and (2) the files are unrelated to those used in the lesson. What do people think?

**Comment by marisalim** [comment]
That sounds good to me!

**Comment by gcapes** [comment]
Why not just explain the actual result? That doesn't take away from the learning objective -- spaces separate arguments.

**Comment by marisalim** [comment]
That would work too. In that case, the error for unicorn.dat just needs to be replaced with an actual output from head -n # for unicorn.dat.

**Comment by gcapes** [comment]
Yep - exactly. Are you planning to submit a PR for this @marisalim ?

**Comment by marisalim** [comment]
Yes, I will submit a PR!

**Comment by colinmorris** [comment]
Fixed by #713
