### ISSUE TITLE
Objectives in episode 4: Pipes and Filters

### ISSUE THREAD

**Issue by elenavataga** [swcarpentry/shell-novice#735]
The last objective is listed as:
"Explain Unix’s ‘small pieces, loosely joined’ philosophy."
which does not seem to be covered anywhere in the text.
Apparently it refers to the paragraph starting with:
"This simple idea is why Unix has been so successful. ..."
The paragraph covers well the advantage of many small tools, 
but "loosely joined" does not sound appropriate, 
I suggest to omit this objective.

**Comment by shwina** [comment]
This is an interesting observation, and you're absolutely right. The terminology "loosely joined" is not explained anywhere in the text. Any suggestions how to re-word the objective? One of the objectives of this episode is to demonstrate that the shell provides tools to combine simple programs together to perform complex tasks.

**Comment by elenavataga** [comment]
Something like:
Understand benefits of “pipes and filters” programming model.

**Comment by navjotk** [comment]
Or: "small tools joined on the shell using pipes and filters."

**Comment by Janet429** [comment]
I was also confused by the objective "Explain Unix’s ‘small pieces, loosely joined’ philosophy". 
Maybe the objective could say something like: Explain the advantages of linking small tools together referred to as "pipes and filters"

**Comment by dhanyapushpadas** [comment]
I was also confused by this objective and I think something like  **Explain how to resolve  many complex tasks with small pieces (pipes and filters) together **

**Comment by jls943** [comment]
I agree that this objective could be clearer. Maybe "Explain the 'filters and pipes' philosophy of Unix programs"

I also got stuck on the second objective, which currently reads "Process a file instead of keyboard input using redirection." It definitely took me a little while to rearrange this enough in my mind so that it made sense. Could it be instead, "Process a file using redirection instead of direct keyboard input." or even more simply, "Process a file using redirection." I think either would work, and both are clearer to my mind than the current version.
