### ISSUE TITLE
Suggested addition to  Learning Objectives

### ISSUE THREAD

**Issue by GBRU-LLB** [swcarpentry/shell-novice#805]
I am attending the Train the Trainers USDA event with Kari and SherAaron.
In The Unix Shell, Working With Files and Directories https://swcarpentry.github.io/shell-novice/03-create/ lesson, perhaps File/Directory Naming Conventions should be a learning objective.

---

**Comment by rikutakei** [comment]
I totally agree with having a good file naming conventions, but I'm not sure if it's necessary to make it an objective. 

I mean, you learn file naming conventions anyway as a result of learning `mkdir`, and if you don't have a good file naming convention, you don't end up making the directory as the person have intended to.

If you don't have good naming convention, then you can't really achieve the first learning objective of the lesson ("Create a directory hierarchy that matches a given diagram"), so I think it's important to emphasize this objective more during the lesson, rather than creating new objectives.

**Comment by gcapes** [comment]
@rikutakei makes a good point that it is implicit in the first objective. This wouldn't be a primary learning objective, so I think we can leave things as they are?
