### ISSUE TITLE
Providing a VM for the Shell Novice lessons using Vagrant

### ISSUE THREAD

**Issue by MattForshaw** [swcarpentry/shell-novice#83]
Good morning,

In the past academic year I used V5.2 of the Software Carpentry lessons with my students and found the experience to be an extremely positive one. The only snag I encountered were inconsistencies between the filesystem on the VM (username swc rather than nelle, and quite a few others besides).

I was interested to see in the V5.3 lessons that there is no longer mention of a virtual machine image, as I found the VM to be a very useful way to ensure a consistent working environment across a wide range of devices (in my teaching context there is significant student preference over machines, so BYOD is common). 

My experience with the V5.2 lessons lead me to wonder whether a Vagrant-based [1] approach to providing a definition of the virtual machine would be of interest to the wider community?

This approach would give us the ability to store in Github a very lightweight description of the virtual machine image, its dependencies, and the file structure, which could more easily be kept consistent and up-to-date with changes to the course materials (with previous snapshots of the Vagrant file meaning we could go back to any previous state of the lesson and reproduce a compatible Virtual Machine).

There would be the possibility for students to download an install Vagrant on their own machine, and to obtain the image themselves (a very simple process taking no more than 5 minutes), or the instructor could do this on their behalf and provide the required VirtualBox files to each student (akin to how things were done in V5.2). The latter would be particularly beneficial in situations where internet connections are slow, alleviating the need for a ~1.7Gig download from a Software Carpentry mirror for each of n students in the class.

I would be very interested to hear everyone's thoughts on this, and this would be an area of development I would be more than happy to take a lead on.

All the best,
Matt

[1] https://www.vagrantup.com/

**Comment by gvwilson** [comment]
Hi Matt,

We've explored various virtual machine options over the years, and while 
some instructors are fans, my experience hasn't been as positive.

1. We almost always have a mix of Windows and Mac users in our 
workshops.  Asking them to learn a new OS while they're also learning 
basic programming is a double burden.

2. Moving information back and forth between the native desktop and the 
VM is always a problem.  (I struggle to remember how to copy and paste 
into Inkscape on my Mac, since it's using X Windows keybindings...)

3. What happens after the workshop?  Learners have to either keep the VM 
going (which one described as having an overnight guest turn into an 
uninvited roommate) or figure out for themselves, on their own, how to 
install equivalent software in their native desktop without us there to 
help.

Another option is to have learners SSH to VMs in the cloud.  Some of our 
instructors who work in bioinformatics advocate this because it's what 
people are going to do anyway - you just can't do real work on a 
desktop.  That puts us at the mercy of the network, though, and we often 
have situations where some of the class can't get on (because they're 
not from the university that's hosting the event, and the promised guest 
accounts don't work) or the WiFi won't handle the load (more common).

There's more discussion of this in `instructors.md` in this repo - could 
you please look it over and tell us what you think needs to be fleshed 
out?  The world's always changing around us, so everything I've said 
above could now be out of date...

Cheers,
Greg

**Comment by jduckles** [comment]
I'm with you on the motivation, but I agree with Greg that there are just too many hiccups to overcome at present to keep the experience usable and consistent for learners. 

One other problem I've seen is that there is no telling what kind of computer a learner will come to a workshop with. When serving less hard-science disciplines where users primary experience with their device is in text generation, they may not have the RAM or CPU to support running a VM. I've had Windows Vista and various laptops that currently meet the learners needs, but could never run a VM on top.

I think it IS a worthwhile effort to have a VM/Vagrantfile/Dockerfile available. I just don't think we're to a point yet where we should recommend the VM for all workshops.

**Comment by jiffyclub** [comment]
We do have this [linux-vm repo](https://github.com/swcarpentry/linux-vm) where I was supposed to put my [puppet manifest](https://gist.github.com/jiffyclub/5512074) (which is used to make the Lubuntu VM @MattForshaw referred to). I wouldn't be opposed to hosting Vagrant or Docker recipes there too, but we'd have to make clear that they wouldn't necessarily be maintained (which makes me wonder whether we *should* accept them).

For long-format courses there are [others](http://bce.berkeley.edu/) going the VM route. In a long class you can devote time to training people up in a VM and finding alternatives for people who can't run it. But in our two-day courses VMs are one more thing to cause problems, and don't as readily prepare people for continuing to use our tools as setting up their own systems.

**Comment by gvwilson** [comment]
On 2015-02-17 1:46 AM, Matt Davis wrote:
>
> We do have this linux-vm repo 
> <https://github.com/swcarpentry/linux-vm> where I was supposed to put 
> my puppet manifest <https://gist.github.com/jiffyclub/5512074> (which 
> is used to make the Lubuntu VM @MattForshaw 
> <https://github.com/MattForshaw> referred to). I wouldn't be opposed 
> to hosting Vagrant or Docker recipes there too, but we'd have to make 
> clear that they wouldn't necessarily be maintained (which makes me 
> wonder whether we /should/ accept them).
>

Given our experiences to date, I think it's better to not have something 
than to have something that isn't going to be maintained.
>
> For long-format courses there are others <http://bce.berkeley.edu/> 
> going the VM route. In a long class you can devote time to training 
> people up in a VM and finding alternatives for people who can't run 
> it. But in our two-day courses VMs are one more thing to cause 
> problems, and don't as readily prepare people for continuing to use 
> our tools as setting up their own systems.
>
+1.

**Comment by aaren** [comment]
If it's not going to be maintained then perhaps the link to the VM should be removed from the workshop template? 

If it is going to be maintained, then see https://github.com/swcarpentry/workshop-template/issues/135 - the current vm is out of date.

**Comment by gdevenyi** [comment]
Another problem with the vagrant route is that many contributors to SWC have neither the time nor inclination to learn how to setup such containers. I want to learn then for my work and I haven't had the time either. 

A bigger problem beyond just shell is the simplicity of integrating other SWC tools, and I think the problem quickly explodes when we consider that.

Closing for now as I think point this has been discussed to death. Will be revived at a later date again.
