### ISSUE TITLE
Episode 1: `ls -F` never fully explained, and introduced before `ls`

### ISSUE THREAD

**Issue by minji011** [swcarpentry/shell-novice#846]
Instead of jumping straight into "ls -F" command, it'd be good to demonstrate with "ls" first and then go to "ls -F".

**Comment by gcapes** [comment]
Keeping related discussion together, @hollybik commented in #901 that
 > The first few unix shell lesson subsections switch between ls and ls -F without ever really explaining why.

**Comment by gdevenyi** [comment]
Related to #166 

This is partially here to force ls to make everyone's output at least somewhat the same.

I think the solution to #166 + switching to ls first is the right solution here.

**Comment by megane0-0** [comment]
I agree @gdevenyi idea. As an instructor candidate, when I practiced to teach "ls" command, I thought it was a little bit confusing to introduce "ls -F" without explaining "-" or "-F" for me.

**Comment by suzerice** [comment]
I agree on all of this. It's especially odd that `ls -F` is first used in "Introducing the Shell", but not broken down and explained until the next lesson, "Navigating Files and Directories". It's almost easier (I actually think it is easier) to teach the second lesson before the first one, since that breaks down `ls`. 

On the basic introduction page, under "What does it look like?", that could just be `ls`, letting the following discussion be just about what the shell is (you type in some commands and the computer does some stuff) versus diving straight into flags. You could also diversify with `pwd` and `ls` as two basic and easy commands, thus keeping the 'introducing the shell' lesson about using different commands in the shell, not looking at specific flags for a specific command.  This relates to the learning objective of "What is a command shell and why would I use one?", which is a much more basic LO than covering flags.

All the flag explanation could then be moved to under the `ls` mention of "Navigating Files..".

That way, it's a more logical order of:

(Introduction to Shell)
- What is the shell?
- What are commands? (`pwd`, `ls`)

(Navigating Files..)
- Home directories
- Slashes
- Command flags

**Comment by gcapes** [comment]
@suzerice 
I like that order of concepts. I do like the existing material but agree the order isn't right.

PR anyone?

**Comment by gdevenyi** [comment]
We'll have to be careful about reordering to make sure cross-references or prereqs don't get messed up.
