### ISSUE TITLE
Using wildcards with the rm command

### ISSUE THREAD

**Issue by sjmillerAZ** [swcarpentry/shell-novice#870]
Please delete the text below before submitting your contribution. 

---
It's dangerous to suggest to beginners that they use wildcards with the rm command. For example, if one accidentally types a space character before the wildcard in the command
rm 2016-05-20-data/raw/*

the results could be seriously bad. I would recommend including that caution in the exercises. Or perhaps add a question that asks what would happen if an accidental space was present in the command.

---

**Comment by mistydring** [comment]
[Hi, Susan!]

I agree with this concern. I noticed elsewhere there was also discussion about the -i flag, and its (possibly redundant) introductions in the examples. I would suggest adding something like the following notes to the section "Deleting Is Forever," so that all learners will cover this material, regardless of which exercises they do:

Because rm permanently removes files from your computer, we suggest two precautions which will help you avoid serious mistakes.
1) Use special care when using wildcards (*, ?) as this will remove any files that follow a particular pattern
2) Use rm in combination with -i, especially if you do decide to use wildcards. The -i flag will prompt the shell to ask you for confirmation prior to each step in the removal procedure, so you will have an opportunity to make sure the command is working as you expect and only removing files you are sure you want to delete.

**Comment by gdevenyi** [comment]
Hi @sjmillerAZ 

I only see wildcards with rm are only introduced at the end of episode 3, and PR #918 will actually remove/rewrite that exercise.

Beyond that content, do you have any places where this is the case?

**Comment by gcapes** [comment]
Thanks for the contributions. I think #918 has removed the only instance of `rm` with wildcards, but please re-open this issue if we've missed something.
