### ISSUE TITLE
Pipes and Filters hint on question about uniq command

### ISSUE THREAD

**Issue by sjmillerAZ** [swcarpentry/shell-novice#876]
Please delete the text below before submitting your contribution. 

---

In the  Pipes and Filters lesson, elaborate on the Hint to the question: Why Does uniq Only Remove Adjacent Duplicates?

There is a hint to think about very large data sets, but that's not enough for me to come up with the answer.

---

**Comment by colinmorris** [comment]
So it seems like this exercise poses 2 questions:

1. Why do you think uniq only removes adjacent duplicated lines? (Hint: think about very large data sets.) 
2. What other command could you combine with it in a pipe to remove all duplicated lines?

Curiously, the solution only answers 2, not 1. Which seems like a pretty big oversight. Would adding an answer to 1 in the solution section address your concern? Or do you think we should also give a more detailed hint in the question body?

**Comment by sjmillerAZ** [comment]
I think for novices it would be best to add an answer to question 1, or even do that in addition to giving a more detailed hint. I think what the hint may be trying to get at is the difficulty of efficiently implementing the uniq filter to remove non-adjacent duplicate lines, but if that’s not correct then I’m still stumped ☺

Thanks,
Susan

**Comment by sjmillerAZ** [comment]
Agreed.  Another option would be to remove the question sine there’s already plenty of material.

**Comment by jttkim** [comment]
The complexity consideration of an all vs. all comparison is entirely true and sensible, but it's not what I'd expect of a shell novice who quite possibly may not have had any exposure to programming. I agree that the "think of large data sets" seems to be designed to lead learners towards that consideration, but strangely, that hasn't occurred to me on the occasions I've discussed this question. Instead, I've considered it as an opportunity to firm up orthogonality and the "do one thing well" design -- since the `sort` and `unique` can be used to compose a command to remove all duplicates, there's no need for a separate command for that purpose.

**Comment by colinmorris** [comment]
Marking this as a bug, due to the absence of a solution to the "Why do you think uniq only removes *adjacent* duplicated lines?" question. PRs welcome!

Given the theoretical nature of the question, I'd suggest we also mark it as a 'bonus', so learners are less likely to get stuck on it, or feel discouraged about not being able to solve it.

Or if someone wants to open a PR to remove this half of the exercise, I don't think that would be unreasonable either.

**Comment by gcapes** [comment]
Thanks for bringing this up. I think we need to focus on the learning objectives here.

The memory-usage consideration, while interesting, doesn't address any of the learning objectives, so I think we should drop that hint rather than providing an explanation. The learning objective that this part of the question relates to is the 'small pieces, loosely joined' idea, however I don't think `uniq` is a very good example to use due to its misleading name (it only detects unique adjacent lines).

The lesson already contains a better example in `wc` which doesn't tell us the shortest/longest file - it just counts. We can find the shortest file using the pipeline in the lesson which uses `sort`. 

As such I would be in favour of removing the whole exercise -- as previously noted, there is already plenty of exercise material for this episode.

**Comment by sjmillerAZ** [comment]
I completely agree with Gerard about removing the exercise in question.


Regards,
Susan Miller
Deputy Director for Research Cyberinfrastructure
UA Data Science Institute (Data7)
University of Arizona

________________________________
