### ISSUE TITLE
Ep4 confusing file name `animalsUpd.txt`

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#937]
http://swcarpentry.github.io/shell-novice/04-pipefilter/index.html#appending-data

What is the significance of this file name? It doesn't mean anything to me, and I guess might also be a source of confusion to learners.

Initial discussion on #853 suggested something to do with garbage collection. I would suggest `animals-subset.txt` or `animals-middle.txt` or something like that, so the file name better describes the content.

**Comment by suzerice** [comment]
I agree. The point of this section is to learn about `tail`, and a student trying to make sense of the file name just detracts from the lesson. 

As for name suggestions, `animals-middle.txt` I don't think quite works (since it's basically going to be anything but the middle, and there's also a question asking what the file will contain), but I really like `animals-subset.txt`.
