### ISSUE TITLE
wc clarity

### ISSUE THREAD

**Issue by alouyakis** [swcarpentry/shell-novice#963]
The Unix Shell: Lesson 4. Pipes and Filters
Word count without flags is used to initially introduce the command and outputs three points of data - character, word, and line count. Then -l is added to show how line count is attained. It would be helpful to also include wc -cwl to show that the output is the same as default without flags. This would help by teaching about default flags and also increase exposure to varied usage by showing -c and -w in addition to -l. A possible addition (without showing the output):
```
$ cd molecules
$ wc *.pdb
```
The default flags for the wc command are -cwl. If we run wc -cwl instead of just wc, the output will be identical:
```
$ wc -cwl *.pdb
```
Each flag can also be used individually. By running wc -l instead of just wc, the output shows only the number of lines per file:
```
$ wc -l *.pdb
```

**Comment by gdevenyi** [comment]
Thanks for the suggestion, a PR would be welcome to discuss default options.

**Comment by jackVanish** [comment]
I'm not sure the Pipes and Filters place is the right lesson for this. I agree that teaching about default flags would be useful, but it seems like it's a little disjoint from the learning objectives of the Pipes and Filters lesson. 

What I think might be a better solution would be to take the 'General Syntax of a Shell Command', which is currently buried in the 'Navigating Files and Directories' lesson, and break it out to its own distinct lesson. This would tighten the focus of the Navigating Files and Directories lesson to only showcase cd, ls, and pwd, as well as lay the groundwork for later lessons with more clarity. This lesson could build on the material already in the 'General Syntax of a Shell Command', as well as incorporate the material on default flags using wc. That dovetails well, since the default flags are mentioned in the wc man page.

**Comment by jackVanish** [comment]
I've pulled down the code and branched it, but I can't seem to push it up to open a pull request. Can anyone set me straight here?

**Comment by gcapes** [comment]
@jackVanish
You would need to fork the repo first, clone your fork, then make changes in a new branch, push them to origin (your fork) and create a pull request from there.

I can help with more details if required.
Thanks

**Comment by jackVanish** [comment]
Thanks very much. I've laid the base work for this in a pull request here: https://github.com/swcarpentry/shell-novice/pull/992. I think there are probably some minor tool-ups left, but I leave that to those more experienced than I to work out. I'm happy to take them on if someone identifies where I've fallen short.

**Comment by gcapes** [comment]
Given #992 is closed, I'm going to close this issue. I guess the lesson is probably full enough already.
