### ISSUE TITLE
Ep7 Using grep: Option used before its introduction

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/shell-novice#981]
The `-E` option hasn't yet been explained.

http://swcarpentry.github.io/shell-novice/07-find/index.html

> Which command would result in the following output:

    and the presence of absence:
> 1.    grep "of" haiku.txt
> 1.    grep -E "of" haiku.txt
> 1.    grep -w "of" haiku.txt
> 1.    grep -i "of" haiku.txt

I think the easiest solution is just to remove this option.

**Comment by amanda-tan** [comment]
But isn't the purpose of this exercise also to help one understand how to use grep --help?

**Comment by gcapes** [comment]
Yeah I guess so. I'll leave the issue open for a while in case others want to add their thoughts.

**Comment by shervinsahba** [comment]
Both of your points makes sense, but I think the inclusion of the choice is good.

Command line users will at some point be confronted with unfamiliar flag options and jargon heavy documentation. It may be unsettling to assess `grep -E` without understanding regular expressions, but such scary encounters are a necessary part of earning your UNIX black belt. In this multiple choice question, a novice may be unsure that `grep -E` will do the job, but they ought to conclude that `grep -w` will do the job.

**Comment by rmaharj17** [comment]
Since, they have already tested the use of command 'grep -w' in the above examples, so I guess they can answer this multiple choice question exactly. The command 'grep -E' in this example makes students , if they tested the code, familiar about how this code works and also they have to deal with the same command in the following example.
So, I think this option 'grep -E' will help students explore more about other commands of 'grep' with different flags listed on 'grep --help'.

**Comment by gcapes** [comment]
Great, thanks all for the input!
