### ISSUE TITLE
 Clarification for 'Loops' lesson in the Unix shell 

### ISSUE THREAD

**Issue by lshapiro31** [swcarpentry/shell-novice#991]
The first time I went through this lesson I was a bit confused by the rationale for the first loop at the top of the lesson. I am wondering if it might be clearer to show the field in the data files we are looking to isolate before running the loop? 

So for example, after this block of text:

Suppose we have several hundred genome data files named basilisk.dat, unicorn.dat, and so on. For this example, we’ll use the creatures directory which only has two example files, but the principles can be applied to many many more files at once. We would like to print out the classification for each species, which is given on the second line of the file. 

[ _Here add the following command to execute before running the loop_]

$ head -n 5 basilisk.dat unicorn.dat 
==> basilisk.dat <==
COMMON NAME: basilisk
CLASSIFICATION: basiliscus vulgaris
UPDATED: 1745-05-02
CCCCAACGAG
GAAACAGATC

==> unicorn.dat <==
COMMON NAME: unicorn
CLASSIFICATION: equus monoceros
UPDATED: 1738-11-24
AGCCGGGTCG
CTTTACCTTA

---

**Comment by gcapes** [comment]
Hi @lshapiro31 

Is the confusion that the content of the files hasn't been shown, which means you're not sure what to expect as the output of the loop? Because the lesson does already explain that we want to print out the second line of the file. We could `cat` one of the files to show an example (which I think I usually do when teaching this), then move on to the rest of the explanation.

Would that address the problem?

Thanks

**Comment by mgibbswalton** [comment]
Yes!  So I just finished demo teaching this exact lesson, and I think a  cat command prior to running the loop to "know your data" would make a lot of sense.  It does say "We would like to print out the classification for each species, which is given on the second line of the file", but a I do think a cat would be good to do within this context:

Change We would like to print out the classification for each species, which is given on the second line of the file.

to

We would like to print out the classification for each species, which is given on the second line of the file as shown in the command below (for the basilisk.dat file)
cat basilisk.dat
 1  COMMON NAME: basilisk
     **2  CLASSIFICATION: basiliscus vulgaris**
     3  UPDATED: 1745-05-02
....

**Comment by kathrynnapier** [comment]
I have just been running through this lesson in preparation for a demo and found myself providing some context on the structure of the file by viewing it first and explaining it really helped me with the flow of the lesson. I agree with the suggestion by @mgibbswalton on changing the text slightly to make this a bit clearer.

Instead of using `cat` , I found using `head -n 5 basilisk.dat minotaur.dat unicorn.dat` as suggested by @lshapiro31 worked a bit better- you can see the structure of the two files is the same, and as the files are long, you can see the head of the files easily.

Suggested slight amendment to the text to explain the structure of the files:
"In the `creatures` directory, we have three genome data files named `basilisk.dat, minotaur.dat, unicorn.dat` . The structure of these files is the same: the common name, classification, and updated date are presented on the first three lines, with DNA sequences on the following lines."

`head -n 5 basilisk.dat minotaur.dat unicorn.dat`

"We would like to print out the classification for each species, which is given on the second line of each file. For each file, we would need to execute the command `head -n 2` and pipe this to `tail -n 1.` In this particular example we only have 3 files, but imagine if we had hundreds of files- we can therefore use a loop to perform the same action on many different files. Firstly, let's look at the general form of a loop:"

**Comment by gcapes** [comment]
This looks good! PR anyone?

**Comment by kathrynnapier** [comment]
@gcapes I can get onto the PR tomorrow.

**Comment by kathrynnapier** [comment]
https://github.com/swcarpentry/shell-novice/pull/1019
